//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanVien_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOKEN
    {
        public int MaToken { get; set; }
        public string KhoaToken { get; set; }
        public Nullable<System.DateTime> ThoiGianCap { get; set; }
        public Nullable<System.DateTime> ThoiGianHetHan { get; set; }
        public Nullable<System.DateTime> ThoiGianTao { get; set; }
        public Nullable<int> MaNV_PB { get; set; }
    
        public virtual NHANVIEN_PHONGBAN NHANVIEN_PHONGBAN { get; set; }
    }
}
